PERSONAL_INFORMATION:
  lastname: 'Kamdem'
  firstname: 'Patrick'
  birthday: '04/05/1991'
  birthplace: 'Yaounde'
  city_of_residence: 'Douala'
  phone_number: '698815310'
  tutor_name: 'Nyobe Roger'
  tutor_phone_number: '694302016'
  father_fullname: 'Kamdem Olivier Philippe'
  father_phone_number: '632101566'
  mother_fullname: 'Njock Christine'
  mother_phone_number: '645531048'